### ISSUE TITLE
Incorrect name reference for parts_library in the BIM Welcome dialog

### ISSUE THREAD

**Issue by frodeseverin** [yorikvanhavre/BIM_Workbench#106]
The BIM Welcome dialog lists a few addons that can enhance the functionality of the BIM Workbench.
Please see attached image.
![Error on clicking link](https://user-images.githubusercontent.com/531708/216826392-acc7a477-5049-4d47-b149-573e859f8607.png)

One of the addons listed is called "Parts Library". Now, the addon manager does not have an addon by that name. There is, however an addon named "parts_library".

I suppose this is the addon in question.
I also suppose the name should be updated, either in the BIM Welcome dialog, or in the name of the addon in Addon Manager.

**Comment by yorikvanhavre** [comment]
Related: https://github.com/FreeCAD/FreeCAD/issues/8361
