### ISSUE TITLE
BIM Tutorial step 12 "select CTH" -> only "CHS" is available

### ISSUE THREAD

**Issue by nelsonic** [yorikvanhavre/BIM_Workbench#109]
Hi Fellow BIM-ers, I'm a noob trying to follow the BIM Tutorial. 
On page/step 12 (of 22) The instructions say "select CTH" 
![image](https://user-images.githubusercontent.com/194400/230484582-286bec9d-b7a7-4549-b0d7-575740d6e897.png)

However "CTH" is not one of the options:

![image](https://user-images.githubusercontent.com/194400/230485103-6c0e401b-d9cc-4367-9089-dc9371a0cd1f.png)
![image](https://user-images.githubusercontent.com/194400/230485621-93574331-a2f6-490f-8c32-7ca052eeb909.png)

Only "CHS" (Circular Hollow Sections)...

Selecting "CHS" allows me to complete the step.
Could be worth updating as it could be a stumbling block for some people. 💭 

# Info

```
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.2.29603 (Git)
Build type: Release
Branch: releases/FreeCAD-0-20
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/United Kingdom (en_GB)
Installed mods: 
  * BIM 2021.12.0
  * Help 1.0.3
  * LCInterlocking
```

**Comment by yorikvanhavre** [comment]
Indeed the whole profiles table has been fixed recently..
Ok the tutorial is fixed: https://wiki.freecad.org/index.php?title=BIM_ingame_tutorial
Thanks!
