### ISSUE TITLE
Slab IFC export fail

### ISSUE THREAD

**Issue by tibohu** [yorikvanhavre/BIM_Workbench#110]
Hi there,
I created a slab, selected and exported the object as IFC.
But unfortunately the saved model is incomplete. The right image shows the result in an IFC-viewer.
What I am missing?

[SlabExpFail.zip](https://github.com/yorikvanhavre/BIM_Workbench/files/11474104/SlabExpFail.zip)
![image](https://github.com/yorikvanhavre/BIM_Workbench/assets/26720708/f7498bcc-878b-430e-8056-9e613923ce67)

**Comment by yorikvanhavre** [comment]
Hm interesting... Obviously the slab is treated wrongly as a single extrusion. This must be fixed in the Arch exporter, I'll fix that ASAP
