### ISSUE TITLE
[minor] typo in "FreeCAD BIM development news September 2018" post

### ISSUE THREAD

**Issue by strixaluco** [yorikvanhavre/BIM_Workbench#12]
This is just a minor typo in a [video](https://github.com/yorikvanhavre/BIM_Workbench/wiki/FreeCAD-BIM-development-news---September-2018#the-video) section, which reads as https://www.youtube.com/Jc12_G5DFF0, but has to be **https://www.youtube.com/watch?v=Jc12_G5DFF0**

**Comment by yorikvanhavre** [comment]
Fixed, thanks!!

**Comment by strixaluco** [comment]
You're welcome. Thank you for your development efforts!
