### ISSUE TITLE
BIM Setup fails with "object has no attribute unitLabel

### ISSUE THREAD

**Issue by tarioch** [yorikvanhavre/BIM_Workbench#126]
I did a fresh installation of 0.21.1 and then installed BIM Workbench, afterwards when I try to run BIM Setup it fails with

```
19:57:44  Running the Python command 'BIM_Setup' failed:
Traceback (most recent call last):
  File "C:\Users\patri\AppData\Roaming\FreeCAD\Mod\BIM\.\BimSetup.py", line 353, in Activated
    statuswidget.unitLabel.setText(

'PySide2.QtWidgets.QToolBar' object has no attribute 'unitLabel'
```

It's running on Windows if that is important.

**Comment by p-himik** [comment]
@yorikvanhavre Seems like this change has broken the setup: https://github.com/yorikvanhavre/BIM_Workbench/commit/db1778a79f392caaf7f449186622639fe1e8683b#diff-50b439d935ab4285556ec48c69c6c55b90b66c721b28e9718daf0bbe1a97d696L292

**Comment by p-himik** [comment]
As a temporary workaround, I went to the directory where FreeCAD is installed, then into `common/Mod/BIM`, and ran `git checkout c4776c1e817202f5aea84ff710acc5de6ed2189d` (the commit before the linked change). After that, the setup dialog seems to be working.

**Comment by yorikvanhavre** [comment]
Thanks! Should be fixed now!
