### ISSUE TITLE
 BIM Preflight check test for IFCv4 support fails quietly on python >= 3.9

### ISSUE THREAD

**Issue by mrevl** [yorikvanhavre/BIM_Workbench#134]
In https://github.com/yorikvanhavre/BIM_Workbench/blob/master/BimPreflight.py
Context: 
from packaging import version
cur_version = version.parse(ifcopenshell.version)
 if type(cur_version) == version.LegacyVersion:

However as per python 3.9 LegacyVersion got removed, which then quietly causes
except Exception as e:
                        self.failed(test)

to get thrown.

Ideas:
-remove the check on LegacyVersion
-test for python <3.9

In this case it looks like a workaround for a problem that wasn't supposed to exist in the first place, haven't looked into this too deeply yet.

For more info see 
https://github.com/pypa/packaging/issues/530

**Comment by yorikvanhavre** [comment]
Hopefully fixed now! Thanks for reporting!
