### ISSUE TITLE
IFC layer creation fails

### ISSUE THREAD

**Issue by talmacsi** [yorikvanhavre/BIM_Workbench#143]
1. freecad 0.21.2
2. switch to BIM workbench
3. creating a new BIM/IFC project (with project, site, building, levels) - success
4. trying to create ifc layer, with "Manage layer"
5. I can only make simple freecad layer, but when I want to switch the layer to IFC layer, I got this error message in report view panel:
`15:37:03  Traceback (most recent call last):
15:37:03    File "C:\Users\talmacsi\AppData\Roaming\FreeCAD\Mod\BIM\.\BimLayers.py", line 167, in accept
15:37:03      import ifc_tools
15:37:03    File "C:\Program Files\FreeCAD 0.21\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
15:37:03      return original_import(name, *args, **kwargs)
15:37:03  ModuleNotFoundError: No module named 'ifc_tools`

I'm not a python coder.

I've tried this in 2 laptops (win10 & win11), both were a fresh install - results were exactly the same.

**Comment by yorikvanhavre** [comment]
This is already fixed in FreeCAD, the BIM workbench is now fully integrated in FreeCAD 1.0, that will be released in a couple of weeks
