### ISSUE TITLE
BIM: There is no up-to-date python documentation for nativeIFC functionality

### ISSUE THREAD

**Issue by tibohu** [yorikvanhavre/BIM_Workbench#144]
Hi there! I tried to do"import ifc_import" via the python console with both 0.21.2 and 1.0.0RC2.
As described on https://github.com/yorikvanhavre/FreeCAD-NativeIFC/blob/main/doc/README.md#import-an-ifc-file
(For both versions, the required addon is installed ifcopenshell as well. The ifcopenshell import is successful.)
But both cases are unsuccessful at "import ifc_import".

**Comment by yorikvanhavre** [comment]
Note that in v1.0RC nativeIFC is fully integrated into BIM, you don't need to install anything else anymore. But you need to do `from nativeifc import ifc_import` instead of just `import ifc_import`.

If this still gives errors, can you please copy here the text of the error message?

**Comment by tibohu** [comment]
Dear Yorik! Thank you! This way it works well.
Is there a more up to date version of FreeCAD-NativeIFC tutorial with python snippets than the one I linked above?

**Comment by yorikvanhavre** [comment]
No unfortunately :/ But that's on my todo list. I'll reconvert this issue so we don't keep track
