### ISSUE TITLE
[Improvement] Import more section types (UB, UC, CHS, RHS)

### ISSUE THREAD

**Issue by GreatApo** [yorikvanhavre/BIM_Workbench#24]
Thank you for your great work, I am still trying to play around in FreeCAD.

I would like to import sections (UC, UB, CHS) in the code however I can't find where sections are imported...

**Comment by yorikvanhavre** [comment]
Hi! 

It all happens here:
https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Arch/Presets/profiles.csv
Feel free to add new categories! The more we have, the better.
One thing is important to know: the different existing profile types (C, H, R, RH o U) correspond to a specific class in https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Arch/ArchProfile.py

If you reuse any of them, there is nothing else to do than adding to profiles.csv.

If you need a new kind of profile, however, you will need 1) to make a new class for it, 2) extend the main makeProfile() function to handle your new profile type. These classes are very simple, you'll see.

If you need further help, consider posting on the [forum](https://forum.freecadweb.org), there is more people there to help!

**Comment by GreatApo** [comment]
Awesome, thanks for pointing it out. Hence, the profile types (C, H, R, RH o U) are related to the geometric characteristic of the section in order to create the 3D models. Importing I, H, U and hollow sections is just a matter of copy paste. Then to include angle sections I just need to make a new type (probably copy paste the U :P ).

**Comment by yorikvanhavre** [comment]
Coding is 99% copy/pasting anyway :smile:

**Comment by GreatApo** [comment]
Good morning,

I added all UB, UC, RHS, CHS sections (https://github.com/GreatApo/FreeCAD/blob/master/src/Mod/Arch/Presets/profiles.csv) and they work fine, however, there seems to be an orientation problem which I don't know if it is related to each section.

![Screenshot from 2019-06-09 12-31-03-edit](https://user-images.githubusercontent.com/9620510/59158629-e4ddd380-8ab4-11e9-9781-08203af69bb0.png)

I am following the same place method for all of them: top view -> structure member -> column -> change section -> click on somewhere. HEA sections appear correctly with UC section are placed based on their geometric center with improper length.
Mind that changing the section of the elements based as HEA shows UC correctly.
The same thing happens for other sections too. For example small CHS sections appear properly while large CHS sections are again oriented wrong.

Should I make a pull request with the changes or this is related to the profiles.csv file?
Are there any other changes I should make? I did'n notice sth relative in the ArchProfile.py file...

**Comment by yorikvanhavre** [comment]
Everything seems to work correctly for me, using your profiles.csv...
![Screenshot from 2019-06-10 15-02-29](https://user-images.githubusercontent.com/1136856/59215903-d533bd00-8b90-11e9-8668-999542a52f49.png)
Are you sure you are using a recent version of FreeCAD? There have been several bugfixes to the structural objects placement recently...

**Comment by GreatApo** [comment]
> Everything seems to work correctly for me, using your profiles.csv...
> ![Screenshot from 2019-06-10 15-02-29](https://user-images.githubusercontent.com/1136856/59215903-d533bd00-8b90-11e9-8668-999542a52f49.png)
> Are you sure you are using a recent version of FreeCAD? There have been several bugfixes to the structural objects placement recently...

Yeah, my mistake, I didn't thought of it. I run the version released in Ubuntu's store. I will see how to compile, test and then pull.
