### ISSUE TITLE
Add version of BIM WB in the WB dropdown menu (like a2plus)

### ISSUE THREAD

**Issue by luzpaz** [yorikvanhavre/BIM_Workbench#28]
Hey @kbwbe where in the a2plus source can this be found? Thanks!

**Comment by yorikvanhavre** [comment]
I don't understand what this issue is about? What are we talking about here??

**Comment by luzpaz** [comment]
![image](https://user-images.githubusercontent.com/4140247/61224565-ce96e900-a6ec-11e9-9540-62db258854a2.png)

**Comment by yorikvanhavre** [comment]
Okay, apparently they added the version number in the workbench name. I would advocate against it, because it makes it hard to detect or translate (the day we are able to translate WB names)...

**Comment by luzpaz** [comment]
Could we not do (hypothetically) `"translate() + version()"` ?

**Comment by yorikvanhavre** [comment]
Theoretically yes, but it's been years that we're discussing WB name translation, so this is unlikely to happen anytime soon

**Comment by luzpaz** [comment]
In that case lets just add the version and then when the day arrives when we discuss translation of workbench names then we cross that bridge ? I'm pushing for this because it's very difficult to quickly find the version of installed external workbenches.

**Comment by luzpaz** [comment]
Demo on BIM WB: 
![image](https://user-images.githubusercontent.com/4140247/61230904-fa1fd080-a6f8-11e9-995a-e9ad6055008b.png)

**Comment by yorikvanhavre** [comment]
TBH with you I don't like that. I wouldn't like my WB selector to be cluttered with numbers. If you implement something like that, it should be optional.

**Comment by luzpaz** [comment]
maybe it can be one of those hidden options ?

**Comment by yorikvanhavre** [comment]
What could be done is 1) add a preferences value like "show addon version number". That could be added in one of the pref pages of FreeCAD or in the AddonManager config screen instead. Then 2) instead of the way you used in the PR, check what is the pref value set by the user, and, only if applicable, append the version number like you did.

**Comment by yorikvanhavre** [comment]
I think this is becoming obsolete with recent addon manager developments by @chennes
