### ISSUE TITLE
Error with BIM Properties 

### ISSUE THREAD

**Issue by ng-galien** [yorikvanhavre/BIM_Workbench#37]
Hello,
I'm completely new with FreeCAD and Arch/BIM and Python.
I run Freecad daily on Ubuntu 19.10;
I was trying some tests on it and I have found some errors in the report view when exporting to IFC.
It shows that the IFC property (number of floors) was not correctly parsed.
Then I try to edit IFC properties through the Panel and it gave an error in _BimIfcProperties.py_ File.
I have modified the _updateDicts_ method has showed in the screen shot (sorry for missing pull request), the reference to the property in the dictionary was not correct when adding or modifying it, I don't know about "*VARIES*" case...

`self.objectslist[name][1][prop+";;"+pset]`

![Capture d’écran du 2019-10-22 14-01-42](https://user-images.githubusercontent.com/33391039/67284168-5f901400-f4d5-11e9-80a9-58f6ba2cf27e.png)

Lines **472**, **474** and **477** in the original file _BimIfcProperties.py_ .

It solved the export problem to, but I'm so far to know if this modification is right for other parts of the app.

Thanks!

**Comment by yorikvanhavre** [comment]
Think I got it fixed. Thanks for reporting!

**Comment by ng-galien** [comment]
Thank you, I have just updated the plugin, it works like a charm ;)
