### ISSUE TITLE
Error message "'BIMWorkbench' object has no attribute 'rebar'" produced on workbench start

### ISSUE THREAD

**Issue by alexey-martynov** [yorikvanhavre/BIM_Workbench#43]
BIM Workbench revision: 360a9b104ecaf3303a0f943f8c9b9bb59ee1bf9c
FreeCAD version: 0.18, 0.19-20406
Platform: MacOS, Windows 10 64bit.

**Comment by alexey-martynov** [comment]
It looks like this message is produced when "Reinforcement" add-on is missing.

Is it possible to produce user friendly message about this?

**Comment by yorikvanhavre** [comment]
Definitely. It should still work seamlessly without the rebar addon. Let me check that..

**Comment by alexey-martynov** [comment]
It is passed as parameter without check on 311 (?) line inside Initialize to create submenu.

**Comment by yorikvanhavre** [comment]
Ok should be fixed now!

**Comment by alexey-martynov** [comment]
Works perfect! Thanks.
