### ISSUE TITLE
Error while downloading tutorial

### ISSUE THREAD

**Issue by azmeuk** [yorikvanhavre/BIM_Workbench#44]
Hi. I am using FreeCAD 0.18 with archlinux. When trying to download the BIM tutorial in FreeCAD, this error messages appears:

```
Traceback (most recent call last):
  File "/home/azmeuk/.FreeCAD/Mod/BIM/BimTutorial.py", line 119, in load
    f = open(offlineloc,"w")
FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce type: '/home/azmeuk/.FreeCAD/BIM/Tutorial/Tutorial.html'
```
Actually, the whole `BIM` directory is missing. After creating '/home/azmeuk/.FreeCAD/BIM/Tutorial/', the tutorial download work as expected.

**Comment by yorikvanhavre** [comment]
Should be fixed now. Thanks for notifying!
