### ISSUE TITLE
import Draft missing

### ISSUE THREAD

**Issue by berndhahnebach** [yorikvanhavre/BIM_Workbench#58]
https://github.com/yorikvanhavre/BIM_Workbench/blob/2dc5248610185f38500863aceed2c84136b59c94/BimDiff.py#L27

here it misses a `import Draft`

because of https://github.com/yorikvanhavre/BIM_Workbench/blob/2dc5248610185f38500863aceed2c84136b59c94/BimDiff.py#L177

- change to BIM workbench, do not use any other tool
- use BIMdiff

**Comment by yorikvanhavre** [comment]
Sorry for the delay! Done!
