### ISSUE TITLE
Error at setup if no document open

### ISSUE THREAD

**Issue by 0penBrain** [yorikvanhavre/BIM_Workbench#65]
https://github.com/yorikvanhavre/BIM_Workbench/blob/c736b24474c28345682aabd46967d0f11ee8ee34/BimSetup.py#L216
Shoud be
`        if hasattr(FreeCADGui,"Snapper") and Gui.ActiveDocument:`
To prevent error in called Draft functions if no document is open.

**Comment by yorikvanhavre** [comment]
FreeCADGui.Snapper.setGrid() should actually check itself that there is a document open and just do nothing silently if it's not the case... But I'll check that

**Comment by yorikvanhavre** [comment]
This is solved now actually... forgot to close the ticket
