### ISSUE TITLE
Error when running BIM Setup on FreeCAD 0.19.23074

### ISSUE THREAD

**Issue by russss** [yorikvanhavre/BIM_Workbench#67]
It seems like DraftToolBar has changed in the dev version of FreeCAD, and setup fails to run with the error `'DraftToolBar' object has no attribute 'widthButton'`. The `fontsizeButton` member also no longer exists.

I'm not currently familiar enough with FreeCAD's scripting to work out what to replace these with, but commenting [this block](https://github.com/yorikvanhavre/BIM_Workbench/blob/f2f4057f439d19526d03553db6c7ee65b610cd3d/BimSetup.py#L211-L213) out allows setup to run successfully.

**Comment by yorikvanhavre** [comment]
Thanks for notifying! Fixed!

**Comment by freecadcostarica** [comment]
Just downloaded the Bim from Github and  i cannot setup my proyect, seems that is the  BIM_setup.py thanks for your work!
![BIM SET UP PROBLEM](https://user-images.githubusercontent.com/40668516/105616762-d2ee9880-5d9e-11eb-8917-38a76e1ba278.png)

**Comment by yorikvanhavre** [comment]
Further fix in 6d8c87c .. This should solve the above error
